name: Sync

on:
  push:
    branches: [ main ]

jobs:
  # 任务1: 部署 GitHub Pages
  deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      # 1、检出源码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # 默认只拉取分支最近一次的 commit，可能会导致一些文章的 GitInfo 变量无法获取，设为 0 代表拉取所有分支所有提交
          fetch-depth: 0
      # 2、配置 Git
      # 主要是 quotePath，默认情况下，文件名包含中文时，git 会使用引号把文件名括起来，这会导致 action 中无法读取 :GitInfo 变量
      - name: Git Configuration
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false  
      # 3、安装 PNPM
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
      # 4、安装 Node 环境
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: pnpm
      # 5、安装依赖
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      # 6、打包
      - name: Build
        run: pnpm docs:build
      # 7、部署 GitHub Pages
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
  deploy-gitee-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
            # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
            # 注意替换为你的 GitHub 源仓库地址
            source-repo: "git@github.com:markbang/markbang.github.io.git"
            # 注意替换为你的 Gitee 目标仓库地址
            destination-repo: "git@gitee.com:bang-wu/bang-wu.git"

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
            # 注意替换为你的 Gitee 用户名
            gitee-username: bang-wu
            # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            # 注意替换为你的 Gitee 仓库
            gitee-repo: bang-wu
            branch: gh-pages